Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RescueModifier:
  Enabled: false

Style/BlockComments:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - spec/**/*
    - Gemfile
    - Gemfile.lock
    - flickrgrid.gemspec
